config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  post "find" => "events#find"
  post "vote" => "surveys#vote"
  post "quick_start" => "events#quick_start"

  post "api/get_auth_token" => "api#get_auth_token"
  post "api/check_auth_token" => "api#check_auth_token"
  post "api/save_ppt_settings" => "api#save_ppt_settings"
  post "api/save_question" => "api#save_question"
  get "api/load_ppt_settings" => "api#load_ppt_settings"
  get "api/load_ppt_list" => "api#load_ppt_list"
  post "api/delete_ppt_settings" => "api#delete_ppt_settings"
  get "api/question_types" => "api#question_types"
  get "api/duration_choices" => "api#duration_choices"
  get "api/me" => "api#me"

  get "api/find_user_by_email" => "api#find_user_by_email"
  get "api/me" => "api#me"

  get "stats" => "home#stats", as: :stats
  get "switch_view" => "home#switch_view"

  get "api/:cmd" => "surveys#api"

  post "vote-test" => "surveys#vote_test"

  devise_for :users, :controllers => {:registrations => 'settings'}

  devise_scope :user do
    post "users/reset_api_token" => "settings#reset_auth_token", as: :reset_auth_token
  end

  resources :events do
    member do
      post "quick_start" => "surveys#quick_start"
      post "add_question" => "events#add_question"
      post "exit_question" => "surveys#exit_question"
      get "connected" => "events#connected_users"
      get "export"
      get "latest_survey" => "events#latest_survey"
    end
    resources :surveys do
      member do
        post 'start'
        post 'stop'
        post 'repeat'
        get 'changed'
        get 'changed_aggregated'
        get 'results'
      end
    end
  end

  resources :questions do
    member do
      post 'add_to_own'
    end
    resources :question_comments, only: [:create, :destroy, :index]
    collection do
      post "export"
      get 'import'
      post 'upload'
      post 'share'
    end
  end
  post "questions/:id/transform" => "questions#transform", as: "transform_question"

  get "invitations/new", :as => "invitation"
  post "invitations/deliver", :as => "deliver_invitation"

  get "newsletter_confirm/:token" => "home#newsletter"

  namespace :admin do
    resources :users
    get 'voting_analytics' => 'users#voting_analytics'
  end
  
  get ":id" => "surveys#participate", :constraints => {:id => /[0-9]+/}, :as => :participate

  mount Amnesia::Application.new => "/amnesia" if defined?(Amnesia)

  mount Pingohort::Engine, at: "/pingohort" if defined?(Pingohort)

end

app/views/shared/_ajax_modal.html.erb
<div class="modal fade" id="ajaxModal" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content" style="overflow:scroll; height: 600px;">

		</div>
	</div>
</div>

app/views/shared/_flashes.html.erb
<div class="row">
	<div class="col-md-12">
		<% flash.each do |name, msg| %>
		<div class="alert alert-<%= name.to_sym == :notice || name.to_sym == :success ? "success" : "danger" %>">
			<a class="close" data-dismiss="alert">×</a>
			<%= msg %>
		</div>
		<% end %>
	</div>
</div>

app/views/shared/_google_analytics.html.erb
<% if Rails.env.production? %>
 <% if false # DISABLED && @event.try(:user).try(:allow_external_analytics) != false && (!user_signed_in? || current_user.allow_external_analytics != false) %>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	  ga('create', 'UA-35829703-1', 'auto', {
	    'allowLinker': true
	  });
	  ga('set', 'anonymizeIp', true);
	  ga('send', 'pageview');


	  <%= yield(:ga_js) %>

	</script>
 <% end %>
<% end %>

app/views/shared/_login_modal.html.erb
<div class="modal fade" id="loginModal" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title"><%= t "navigation.login" %></h4>
      </div>
        <div class="modal-body">
	     <%= form_for resource, as: resource_name, url: session_url(resource_name, protocol: ((Rails.env.production?||Rails.env.staging?) ? "https" : "http")), html:{class: 'new_session'} do |f| %>
          <fieldset>
                <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, required: true, autofocus: true, class: "form-control" %>
                </div>

                <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, required: true, class: "form-control" %>
                </div>

                <% if devise_mapping.rememberable? %>
                  <div class="checkbox">
                    <label for="user_remember_me", class="checkbox">
                      <%= f.check_box :remember_me %>
                      <%= t "remember_me" %>
                    </label>
                  </div>
                <% end %>
          </fieldset>
      </div>
      <div class="modal-footer">
        <span style="float:left;">
    			<%= link_to t("forgot_password"), new_password_url(resource_name, protocol: ((Rails.env.production?||Rails.env.staging?) ? "https" : "http")) %> |  
    			<%= link_to t("navigation.sign_up"), new_user_registration_url(protocol: ((Rails.env.production?||Rails.env.staging?) ? "https" : "http")) %>
		    </span>
        <a href="#" class="btn btn-default" data-dismiss="modal"><%= t "close" %></a>
        <%= f.submit t("navigation.login"), class: 'btn btn-primary login_submit_btn' %>
  	   <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
<li class="dropdown">
	<%= link_to icon_tag("flash") + t("navigation.quick_start"), new_event_path, id: "menuQuickstartLink", class: "dropdown-toggle", data: {icon: "icon-plus", toggle: "dropdown", target: "#"} %>
	<div class="dropdown-menu" style="width: 240px; padding-left: 15px; padding-right: 15px;">
		<%= form_tag("/quick_start")%>
		<%= render partial: "shared/quick_start_form" %>
	</form>
</div>
</li>
<li class="dropdown" id="menuEventsLink">
	<a id="sessions" href="#" class="dropdown-toggle" data-toggle="dropdown">
		<%= icon_tag("stats") +  t("navigation.survey_execution") %>
		<b class="caret"></b>
	</a>
	<ul class="dropdown-menu" role="menu">
		<% if current_user.events.any? %>
			<% current_user.events.desc(:updated_at).limit(3).each do |event| %>
				<li><%= link_to "<span class=\"text-muted\">##{display_event_token(event)}</span> – ".html_safe + event.name, event %></li>
			<% end %>
			<li role="presentation" class="divider"></li>
		<% end %>

		<%= content_tag :li, class: (current_page?(events_path) ? "active" : "")  do -%>
			<%= link_to t("navigation.your_events"), events_path %>
		<% end -%>

		<%= content_tag :li, class: (current_page?(new_event_path) ? "active" : "")  do -%>
			<%= link_to t("navigation.new_survey"), new_event_path, id: "menuNewEventLink" %>
		<% end -%>
	</ul>
</li>

<li class="dropdown" id="menuQuestionsLink">
	<a id="questions" href="#" class="dropdown-toggle" data-toggle="dropdown">
		<%= icon_tag("pencil") + t("navigation.survey_design") %>
		<b class="caret"></b>
	</a>
	<ul class="dropdown-menu" role="menu">
		<%= content_tag :li, class: (current_page?(questions_path) ? "active" : "")  do -%>
			<%= link_to(t("navigation.questions_catalogue"), questions_path) %>
		<% end -%>

		<li role="presentation" class="divider"></li>

		<%= content_tag :li, class: (current_page?(new_question_path) ? "active" : "")  do -%>
			<%= link_to(t("navigation.new_question"), new_question_path, id: "menuQuestionsLink") %>
		<% end -%>
		<%= content_tag :li, class: (current_page?(import_questions_path) ? "active" : "")  do -%>
			<%= link_to(t("navigation.import_questions"), import_questions_path, id: "menuQuestionsLink") %>
		<% end -%>
	</ul>
</li>

<% if current_user.admin %>
<li>
	<%= link_to('Admin', admin_users_path(protocol: ((Rails.env.production?||Rails.env.staging?) ? "https" : "http")), ) %>
</li>
<% end %>

<li class="dropdown user-navigation" id="menuSettingsLink">
	<a id="user" href="#" class="dropdown-toggle" data-toggle="dropdown">
		<%= icon_tag("user") + current_user.name %>
		<b class="caret"></b>
	</a>
	<ul class="dropdown-menu" role="menu">
		<%= content_tag :li, class: (current_page?(edit_user_registration_path) ? "active" : "")  do -%>
			<%= link_to(icon_tag("cog") + t("navigation.edit_account"), edit_user_registration_url(protocol: ((Rails.env.production?||Rails.env.staging?) ? "https" : "http"))) %>
		<% end -%>
		<li role="presentation" class="divider"></li>
		<li>
			<%= link_to(icon_tag("lock") + t("navigation.logout"), destroy_user_session_url(protocol: ((Rails.env.production?||Rails.env.staging?) ? "https" : "http")), method: :delete) %>
		</li>
	</ul>
</li>

<% else %>
<li>
<%= link_to(icon_tag("user") + t("navigation.login"), "#loginModal", id: "login", data: {toggle: "modal"})  %>
</li>
<!--
<li>
<%= link_to(t("navigation.sign_up"), new_user_registration_path)  %>
</li>
//-->
<% end %>
<!--<li class="dropdown">
	<a id="help" href="#" class="dropdown-toggle" data-toggle="dropdown">
			<%= icon_tag("info-sign") %>
			<%= t "navigation.about" %> &nbsp;
			<b class="caret"></b>
	</a>
	<ul class="dropdown-menu" role="menu" aria-labelledby="help">
			<li>
					<%= link_to icon_tag("pingo") + t("navigation.project_website"), "http://www.uni-paderborn.de/pingo", :target => "_blank", :hreflang => "de" %>
			</li>
			<li>
					<%= link_to icon_tag("film") + t("navigation.intro_video"), "#pingo_video", data: {toggle: "modal"} %>
			</li>
			<% if user_signed_in? %>
			<li>
					<%= link_to icon_tag("road") + t("navigation.take_tour"), root_path(tour: "true") %>
			</li>
			<% end %>
			<li>
					<%= link_to icon_tag("bullhorn") + "Blog", "http://blogs.uni-paderborn.de/pingo/", target: "_blank", hreflang: "de" %>
			</li>
			<li>
					<%= link_to icon_tag("file") + t("navigation.getting_started"), "/tutorial/tutorial.html", target: "_blank", hreflang: "de" %>
			</li>
			<% if I18n.locale == :de %>
			<li>
					<%= link_to icon_tag("file") + "Didaktische Hinweise", "https://wiwi.uni-paderborn.de/fileadmin/lehrstuehle/department-3/wiwi-dep-3-ls-4/PINGO_Didaktische_Handreichung_Einsatzmoeglichkeiten_final.pdf", target: "_blank", hreflang: "de", title: "Handreichung zu didaktischen Einsatzmoeglichkeiten" %>
			</li>
			<% end %>
			<% if user_signed_in? %>
			<li>
					<%= link_to icon_tag("bookmark") + t("navigation.invite"), invitation_path, rel: "nofollow" %>
			</li>
			<% end %>
	</ul>
</li>-->

app/views/shared/_quick_start_form.html.erb
<div class="checkbox">
  <label for="q_type_single" class="radio">
    <%= radio_button_tag 'q_type', 'single', (quick_start_settings["q_type"]||"single") == "single", class: "type-radio", data: {"survey-type" => "choice"} %> <%= t "type.single" %></label>
</div>
<div class="checkbox">
  <label for="q_type_multi" class="radio">
    <%= radio_button_tag "q_type", 'multi', quick_start_settings["q_type"] == "multi", class: "type-radio", data: {"survey-type" => "choice"} %> <%= t "type.multi" %>
  </label>
</div>
<div class="checkbox">
  <label for="q_type_text" class="radio">
    <%= radio_button_tag "q_type", 'text', quick_start_settings["q_type"] == "text", class: "type-radio", data: {"survey-type" => "text"} %> Text/TagCloud
  </label>
</div>
<div class="checkbox">
  <label for="q_type_number" class="radio">
    <%= radio_button_tag "q_type", 'number', quick_start_settings["q_type"] == "number", class: "type-radio", data: {"survey-type" => "number"} %> <%= t("type.number") %> <span class="label label-info">BETA</span>
  </label>
</div>

<div class="options_container form-group">
  <label for="options"><%= t "quick_start.how_many_options_short" %></label>
  <%= select_tag "options", options_for_select(answer_choices, quick_start_settings["options"]), tabindex: 4, class: "form-control answer-options-select" %>
</div>
<div class="form-group">
  <label for="duration"><%= t "quick_start.how_long_short" %></label>
  <%= select_tag "duration", options_for_select(duration_choices, quick_start_settings["duration"]), tabindex: 5, class: "form-control" %>
</div>


<div class="remember form-group">
    <input class="btn btn-primary" id="new-event-survey_submit" value="<%= t "start" %>" tabindex="8" type="submit" class="inline">
    <label for="remember" class="checkbox pull-right"><input class="checkbox inline" id="remember" name="remember_settings" value="1" tabindex="7" type="checkbox">
    <%= t "quick_start.remember_settings" %></label>
</div>

app/views/shared/_video.html.erb
<%
if I18n.locale == :de
  ytlink = "KK22QMb0MFA"
else
  ytlink = "aZC3NnUqZcs"
end
%>
<div class="modal fade" id="pingo_video" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content" style="width: 700px;">
			<div class="modal-header">
				<button class="close" data-dismiss="modal">×</button>
				<h4 class="modal-title" id="myModalLabel">PINGO Video</h4>
			</div>
			<div id="videoContainer" class="modal-body">
				<!-- iframe will be inserted here as soon as modal loads -->
			</div>
			<div class="modal-footer">
				<small style="float:left;">Link: <%= link_to "http://youtu.be/#{ytlink}", "http://youtu.be/#{ytlink}", target: "_blank", rel: "alternate" %></small>
				<button class="btn btn-default" data-dismiss="modal" aria-hidden="true"><%= t "close" %></button>
			</div>
		</div>
	</div>
</div>
<% content_for :javascript do %>
<script>
var iFrameHTML = '<iframe id="videoiFrame" width="640" height="360" src="https://www.youtube-nocookie.com/embed/<%= ytlink %>?rel=0&enablejsapi=1&origin=<%= ENV["URL_PREFIX"] %>" frameborder="0" allowfullscreen></iframe>';
	$('#pingo_video').on('show.bs.modal', function () {
	$("#videoContainer").html(iFrameHTML);
	});
	$('#pingo_video').on('hide.bs.modal', function () {
		// Remove video
		$("#videoiFrame").remove();
	});
</script>
<% end %>