config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  post "find" => "events#find"
  post "vote" => "surveys#vote"
  post "quick_start" => "events#quick_start"

  post "api/get_auth_token" => "api#get_auth_token"
  post "api/check_auth_token" => "api#check_auth_token"
  post "api/save_ppt_settings" => "api#save_ppt_settings"
  post "api/save_question" => "api#save_question"
  get "api/load_ppt_settings" => "api#load_ppt_settings"
  get "api/load_ppt_list" => "api#load_ppt_list"
  post "api/delete_ppt_settings" => "api#delete_ppt_settings"
  get "api/question_types" => "api#question_types"
  get "api/duration_choices" => "api#duration_choices"
  get "api/me" => "api#me"

  get "api/find_user_by_email" => "api#find_user_by_email"
  get "api/me" => "api#me"

  get "stats" => "home#stats", as: :stats
  get "switch_view" => "home#switch_view"

  get "api/:cmd" => "surveys#api"

  post "vote-test" => "surveys#vote_test"

  devise_for :users, :controllers => {:registrations => 'settings'}

  devise_scope :user do
    post "users/reset_api_token" => "settings#reset_auth_token", as: :reset_auth_token
  end

  resources :events do
    member do
      post "quick_start" => "surveys#quick_start"
      post "add_question" => "events#add_question"
      post "exit_question" => "surveys#exit_question"
      get "connected" => "events#connected_users"
      get "export"
      get "latest_survey" => "events#latest_survey"
    end
    resources :surveys do
      member do
        post 'start'
        post 'stop'
        post 'repeat'
        get 'changed'
        get 'changed_aggregated'
        get 'results'
      end
    end
  end

  resources :questions do
    member do
      post 'add_to_own'
    end
    resources :question_comments, only: [:create, :destroy, :index]
    collection do
      post "export"
      get 'import'
      post 'upload'
      post 'share'
    end
  end
  post "questions/:id/transform" => "questions#transform", as: "transform_question"

  get "invitations/new", :as => "invitation"
  post "invitations/deliver", :as => "deliver_invitation"

  get "newsletter_confirm/:token" => "home#newsletter"

  namespace :admin do
    resources :users
    get 'voting_analytics' => 'users#voting_analytics'
  end
  
  get ":id" => "surveys#participate", :constraints => {:id => /[0-9]+/}, :as => :participate

  mount Amnesia::Application.new => "/amnesia" if defined?(Amnesia)

  mount Pingohort::Engine, at: "/pingohort" if defined?(Pingohort)

end

app/models/event.rb
class Event

  TOKEN_LENGTH = (Rails.env.staging? ? 3 : 4)

  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Token

  include ActiveModel::ForbiddenAttributesProtection # #rails4

  token length: TOKEN_LENGTH, contains: :fixed_numeric

  after_save :delete_cache, :refresh_state

  field :name, type: String
  field :description, type: String
  field :state, type: Integer, default: 0 # note this is not a state in a "state" sense but rather just a "version" indicator
                                          # it is used to make sure views are current (js stuff)
  field :mathjax, type: Boolean, default: false

  field :default_question_duration, type: Integer, default: 0

  field :custom_locale, type: String
  validates :custom_locale, inclusion: {in: I18n.available_locales.map(&:to_s) + [""], allow_nil: true}

  belongs_to :user, inverse_of: :events
  has_many :surveys, dependent: :destroy

  has_and_belongs_to_many :collaborators, class_name: "User", inverse_of: :shared_events
  index({ collaborator_ids: 1 }, { sparse: true })

  validates :name, presence: true
  validates :user, presence: true

  def latest_survey(scope = nil)
    if scope == "participate"
      self.surveys.desc(:created_at).limit(1).participate_fields.first
    else
      self.surveys.desc(:created_at).limit(1).display_fields.first
    end
  end

  def self.find_by_id_or_token(token_or_id)
    if token_or_id.length <= TOKEN_LENGTH && !token_or_id.to_s.blank?
      if token_or_id.to_s.length < TOKEN_LENGTH
        Event.find_by_token("0"*(TOKEN_LENGTH - token_or_id.to_s.length) + token_or_id.to_s)
      else
        Event.find_by_token(token_or_id)
      end
    else
      Event.find(token_or_id)
    end
  end

  def delete_cache
    Rails.cache.delete("Events/"+self.id.to_s)
    Rails.cache.delete("last_survey/"+self.id.to_s)
  end

  def refresh_state
    self.inc(state: 1)
  end

  def current_viewers
    PINGO_REDIS.get("vote_hub/" + (self.token.to_s.gsub(/[^a-zA-Z 0-9]/, "")).gsub(/\s/,'-')) unless ENV["USE_JUGGERNAUT"] == "false"
  end

  def mathjax?
    self.mathjax
  end

  # for FORM

  def collaborators_form
    self.collaborators.map(&:id).join(",")
  end

  def collaborators_form=(v)
    self.collaborators = v.split(",").reject(&:blank?).map do |u|
      User.find(u)
    end
  end

  # for token length upgrade purposes
  def self.check_and_upgrade_all_tokens! # upgrades tokens by padding with leading zeros
    results = []
    errors = []
    puts ""
    all_evt_ids = Event.where("this.token.length < #{Event::TOKEN_LENGTH.to_s}").only(:id).map(&:id)
    puts "#{all_evt_ids.count.to_s} events"
    all_evt_ids.each_with_index do |event_id, i|
      e = Event.find(event_id)
      print "#{i.to_s}: #{e.token.to_s} .. "
      old_token = e.token.to_s
      # FIXME: Warning: The following line adds two zeros (hard coded!). Please adapt for your token length.
      new_token =  "00#{e.token.to_s}" # ("%0#{Event::TOKEN_LENGTH.to_s}d" % e.token.to_s)
      print "#{old_token} -> #{new_token} .. "
      begin
        e.set(:token, new_token)
      rescue ex
        errors << old_token
        puts "..error"
      end
      results << [old_token, e.token]
      puts "..ok"
    end
    [results, errors]
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user_from_token!, :except => [:participate, :find]
  before_action :authenticate_user!, :except => [:participate, :find]
  layout :detect_browser

  # GET /events
  # GET /events.json
  def index
    if(params[:all] && current_user.admin?)
      @events = Event.all.desc(:created_at)
      @events = @events.limit(200) unless params[:all] == 'all'
    elsif params[:shared]
      @events = current_user.shared_events.desc(:created_at)
      redirect_to events_url, alert: "No shared sessions found." and return unless @events.any? # should not occur
    else
      @events = current_user.events.desc(:created_at)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  def latest_survey
    @event = Event.find_by_token(params[:id])
    render json: @event.latest_survey
  end

  # POST /find
  def find
    if params[:id] && params[:id].match(/\A\d{3,}\z/) # at least 3 digits
      redirect_to "/"+params[:id]
    else
      redirect_to root_path, alert: t("messages.survey_not_found")
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find_by_id_or_token(params[:id])
    check_access
    return if performed?

    @surveys = @event.surveys.display_fields.desc(:created_at)

    respond_to do |format|
      format.html { set_locale_for_event_or_survey } # show.html.erb
      format.json { render json: @event, methods: :latest_survey }
      format.csv { export }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find_by_token(params[:id])

    check_access
    return if performed?

  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: t("messages.session_successfully_created") }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find_by_token(params[:id])

    check_access
    return if performed?

    respond_to do |format|
      if @event.update_attributes(event_params)
        current_user.contacts.concat (@event.collaborators - current_user.contacts)
        current_user.save

        format.html { redirect_to @event, notice: t("messages.session_successfully_updated") }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find_by_token(params[:id])

    check_access
    return if performed?

    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :ok }
    end
  end

  # GET /events/1/connected
  def connected_users
    @event = Event.find_by_token(params[:id])
    render plain: (@event.try(:current_viewers) || "-")
  end

  # POST /quick_start
  def quick_start
    @event = Event.new
    @event.name = "Quick Session"
    @event.user = current_user
    @survey = @event.surveys.build
    # @survey.name = t("quick_survey")
    @survey.quick = true

    if Question.question_types.include?(params[:q_type])
      @survey.type = params[:q_type]
    else
      @survey.type = "single"
      params[:q_type] = "single"
    end

    @survey = @survey.service

    if @survey.has_options?

      options = (is_numeric?(params[:options]) ? params[:options].to_i : 4)
      options = 26 if options > 26

      alphabet = %W(A B C D E F G H I J K L M N O P Q R S T U V W X Y Z)

      (1..options).each do |option|
        @survey.options.new(name: alphabet[option-1])
      end

    elsif params[:options] && @survey.has_settings?
      @survey.add_setting :answers, params[:options]
    end

    duration = (is_numeric?(params[:duration]) ? params[:duration].to_i : 0)

    if params[:remember_settings] == "1"
      current_user.quick_start_settings[:q_type] = params[:q_type]
      current_user.quick_start_settings[:options] = options
      current_user.quick_start_settings[:duration] = duration
      current_user.save!
    end

    respond_to do |format|
      if @event.save
        @survey.start!(duration)
        start_countdown_worker(@survey.id) if duration > 0
        format.html { redirect_to @event, notice: t("messages.session_survey_successfully_created") }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new"; puts @survey.errors.messages }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /events/:id/add_question
  def add_question
    @event = Event.find_by_id_or_token(params[:id])

    check_access
    return if performed?

    question = Question.find(params[:question])
    @survey = question.to_survey
    @survey.event = @event

    unless params[:duration].nil?
      duration = (is_numeric?(params[:duration]) ? params[:duration].to_i : 0)
      @event.update_attribute(:default_question_duration, duration) if params[:remember_settings] == "1"
    else
      if @event.default_question_duration
        duration = @event.default_question_duration
      else
        duration = 0
      end
    end

    respond_to do |format|
      if @survey.save
        @survey.start!(duration)
        publish_push_notification("/sess/"+@survey.event.token.to_s, {:type => "status_change", :payload => "started", "timestamp" => Time.new})
        start_countdown_worker(@survey.id) if duration > 0
        format.html { redirect_to event_path(@survey.event), notice: t("messages.survey_successfully_created") }
        format.js
        format.json { head :ok }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /events/:id/export
  def export
    @event ||= Event.find_by_id_or_token(params[:id])

    check_access
    return if performed?

    csv_data = CSV.generate col_sep: "\t", quote_char: '"', force_quotes: true  do |csv|
      # header row
      csv << ['Survey ID', 'Question', 'Question Type', 'Question Options', 'Voter ID', 'Survey Start', 'Survey End', 'Answer']

      # survey objects
      @event.surveys.map(&:service).each do |survey|
        # raw results
        results = survey.raw_results
        options_s = nil

        if survey.respond_to?(:options_s)
          options_s = survey.options_s
        end

        results.each do |result|
          csv << [
            survey.id,
            survey.name,
            survey.type,
            options_s,
            result.voter_id,
            survey.starts,
            survey.ends,
            result.answer
          ]
        end
      end
    end

    send_data csv_data, :type => 'text/csv; charset=utf-8; header=present', :filename => 'PINGO_surveys_'+@event.token+'_'+Time.current.to_s.tr(" ", "_")+'.csv'
  end

  protected
  def event_params
    params.require(:event).permit(:name, :description, :mathjax, :collaborators_form, :custom_locale)
  end

  def check_access
    render plain: t("messages.no_access_to_session"), status: :forbidden and return  if !@event.nil? && !current_user.admin && @event.user != current_user && !@event.collaborators.include?(current_user)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def display_event_token(event)
    if Event::TOKEN_LENGTH > 4
      event.token.to_s.sub(/^00/, "")
    else
      event.token.to_s
    end
  end
end

app/views/events/_advanced_settings.html.erb
<div class="form-group">
  <label for="event_custom_locale">
    <span data-toggle="popover" data-placement="left" data-content="<%= strip_tags(t(".language_tooltip")) %>" title="<%= strip_tags(t(".language_headline")) %>"><%= icon_tag(:globe) %> <%= t ".language_headline" %></span>
  </label>
    <%= select_tag("event_custom_locale_select", options_for_select([[t(".de"), "de"], [t(".en"), "en"]], selected: @event.custom_locale), prompt: "-", class: "form-control") %>
</div>

<% content_for :javascript do %>
<script type="text/javascript" charset="utf-8">
$("#event_custom_locale_select").change(function() {
  $("#event_custom_locale").val($(this).val());
});
</script>
<% end %>

app/views/events/_duration_modal.html.erb
<div class="modal fade" id="durationModal" tabindex="-1" role="dialog" aria-labelledby="durationModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="durationModalLabel"><%= t ".select_duration" %></h3>
  </div>
  <div class="modal-body">
	<%= form_tag "__ACTION__", method: :post, remote: true, id: "duration_modal_form" %>
	<%= hidden_field_tag "question", "", id: "duration_question" %>
	<p>
	   <label for="duration"><%= t "quick_start.how_long_short" %></label>
	      <%= select_tag "duration", options_for_select(duration_choices, quick_start_settings["duration"]), :class => "span3" %>
    </p>
	<p>
		<label for="remember" class="checkbox"><input class="checkbox inline" id="remember" name="remember_settings" value="1" type="checkbox"> 
        <%= t ".remember_settings" %></label>
		<%= submit_tag "start", :class => "btn btn-primary" %>
		</form>
	</p>
  </div>
  <div class="modal-footer">
	<span id="duration_description" class="pull-left">
		&nbsp;
	</span>
    <button class="btn" data-dismiss="modal" aria-hidden="true"><%= t "close" %></button>
  </div>
</div>
<% content_for :javascript do %>
	<script>
		$("#durationModal").modal({show: false});
		$(document).on("ajax:error", "duration_modal_form", function(){
			alert("Leider ist ein Fehler aufgetreten. \n Unfortunately, an error occured.")
		});
	</script>
<% end %>

app/views/events/_qr.html.erb
<div class="modal fade" id="qrModal" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">QR Code #<%= event.token %></h4>
            </div>
            <div class="modal-body">
                <p style="text-align:center;"><%= image_tag "https://chart.googleapis.com/chart?cht=qr&choe=ISO-8859-1&chs=520x520&chl=#{participate_url(event.token)}", size: "200x200", alt: "QR Code", id: "eventQrImg" %><br>
                </p>
            </div>
            <div class="modal-footer">
                <div class="pull-left">
                    <button class="btn" id="zoomQrLink"><%= icon_tag "zoom-in" %></button>
					<strong>pingo.upb.de &rarr; <%= display_event_token(event) %></strong>
                </div>

                <button class="btn btn-default" data-dismiss="modal"><%= t("close") %></button>
            </div>
        </div>
    </div>
</div>

<% content_for :javascript do %>
    <script>
        $(document).ready(function(){
            $("#zoomQrLink").click(function(){
                $("#eventQrImg").attr("height", "520").attr("width", "520").css("margin-top", "0").css("margin-bottom", "0");
                $(this).remove();
            });
        });
    </script>
<% end %>

app/views/events/_quickstart_create_new_question.html.erb
<p><%= t("surveys.create_from_catalogue_text").html_safe %></p>
<%= link_to t("questions.create_question"), new_question_path(redirect_to_session: event.token), :class => "btn btn-primary" %>

app/views/events/_quickstart_exitquestion.html.erb
<%= form_tag(exit_question_event_path(event.token), class: "form-horizontal", remote: true) %>
	<p><%= t("surveys.ask_exit_q") %></p>
	<%= submit_tag t("surveys.exit_question"), :class => "btn btn-primary" %>
</form>

app/views/events/_quickstart_survey.html.erb
<%= form_tag(quick_start_event_path(event.token), remote: true)%>
	<%= render partial: "shared/quick_start_form" %>
</form>

app/views/events/add_question.js.erb
// define here what JS should be executed after adding a question via ajax.
window.PINGO.events.updateSurveyTable("#event-survey-content", "<%= event_surveys_path(@event)%>");
window.PINGO.events.loadSurvey("<%= event_survey_path(@event, @survey) %>");

app/views/events/edit.html.erb
<h1><%= t ".headline" %></h1>
<div class="row">
  <div class="col-md-7">
    <%= render 'form' %>
  </div>
  <div class="col-md-5">
    <%= render "advanced_settings", event: @event %>
    <%= render "collaborators", item: @event %>
  </div>
</div>

<%= link_to t("back"), @event %>

app/views/events/new.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= t ".headline" %></h1>

    <%= render 'form' %>

    <%= link_to t("back"), events_path %>
  </div>
</div>

<% if params[:tour] == "true" %>
 <%= render "tours/enable_tour" %>
 <%= render "tours/events/new" %>
<% end %>

app/views/events/show.html.erb
<% title(@event.token) %>
<script>
	event_page = true;
</script>
<% unless ENV["USE_JUGGERNAUT"] == "false" %>
<% content_for :javascript do %>
    <%= push_script_tag %>
<% end %>
<% end %>
<div id="fullscreen">
	<div class="survey-layout">
		<div class="panel-group accordion" id="new-event-survey-accordion" role="tablist" aria-multiselectable="true">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#new-event-survey-accordion" href="#survey_quickstart_collapse">
						<%= t "events.show.add_survey" %>
					</a>
					</h4>
				</div>
				<div id="survey_quickstart_collapse" class="panel-collapse collapse in">
					<div class="panel-body">
						<%= render "events/quickstart_survey", event: @event %>
					</div>
				</div>
			</div>
			<% if current_user.questions.any? || current_user.shared_questions.any? %>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">
						<%= link_to t(".show_questions"), questions_path(format: :json), data: {target: "#survey_fromquestion_collapse", toggle: "collapse", parent: "#new-event-survey-accordion"}, remote: true, class: "accordion-toggle", id: "show_questions_link" %>
					</h4>
				</div>
				<div id="survey_fromquestion_collapse" class="panel-collapse collapse">
					<div class="panel-body">
						<%= render "events/quickstart_from_question", event: @event %>
					</div>
				</div>
			</div>
			<% end %>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">
						<a class="accordion-toggle" data-toggle="collapse" data-parent="#new-event-survey-accordion" href="#survey_createquestion_collapse">
							<%= t("surveys.create_from_catalogue") %>
						</a>
					</h4>
				</div>
				<div id="survey_createquestion_collapse" class="panel-collapse collapse">
					<div class="panel-body">
						<%= render "events/quickstart_create_new_question", event: @event %>
					</div>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">
						<a class="accordion-toggle" data-toggle="collapse" data-parent="#new-event-survey-accordion" href="#survey_exitquestion_collapse">
							<%= t("surveys.exit_question") %>
						</a>
					</h4>
				</div>
				<div id="survey_exitquestion_collapse" class="panel-collapse collapse">
					<div class="panel-body">
						<%= render "events/quickstart_exitquestion", event: @event %>
					</div>
				</div>
			</div>
		</div>

		<h1><%= @event.name %> <%= link_to display_event_token(@event), participate_path(@event.token), id: "big_token" %>
		<div class="btn-group pull-right">
			<%= link_to icon_tag("pencil"), edit_event_path(@event), title: t("edit"), id: "editEventLink", class:"btn btn-default" %>
			<%= link_to icon_tag("qrcode"), "#qrModal", title: "QR-Code", id: "qrLink", data: {toggle: "modal"}, class:"btn btn-default" %>
			<%= link_to icon_tag("fullscreen"), "#fullscreen", title: t("fullscreen"), id: "fullscreenLink", class:"btn btn-default" %>
		</div></h1>
		<% unless @event.description.blank? %>
		<p class="muted">
			<%= @event.description %>
		</p>
		<% end %>
		<div id="connected-container">
			<%= t ".connected" %>: <span class="badge" id="connected-number">?</span>
		</div>
		<div id="survey-container">
		</div>
	</div>
</div>
<div class="row" id="survey-list">
	<div id="survey-list-left" class="col-md-12">
		<h2><%= t ".surveys" %></h2>
		<div id="event-survey-content">
			<% unless @event.surveys.empty? %>
			<%= render "events/surveys_table", event: @event %>
			<p class="clearfix">
				<div class="btn-group pull-right">
					<%= link_to export_event_path(@event), class: 'btn btn-default' do %>
						<%= icon_tag("file") %> <%= t('events.show.export_results') %>
					<% end %>
					<button class="btn dropdown-toggle btn-default" data-toggle="dropdown">
					<span class="caret"></span>
					</button>
					<ul class="dropdown-menu">
						<li><%= link_to icon_tag("download-alt") + t("events.show.export_results_json"), event_surveys_path(@event, format: :json) %></li>
					</ul>
				</div>
			</p>
			<% else %>
				<p id="event-survey-no-surveys"><%= t ".no_surveys" %>
			</p>
			<% end %>
		</div>
	</div>


	<% content_for :javascript do %>
	<script>
		sound_enabled = <%= current_user.wants_sound %>;
	<% unless @event.surveys.empty? %>
		jQuery.getScript("<%= event_survey_path(@event, (@load_survey || @event.surveys.desc(:started, :created_at).first)) %>", function() {
			if(History){
				$(window).bind('statechange', function(){
					var State = History.getState(), url = State.url;
					window.PINGO.events.loadSurvey(url);
				});
			}
		});
	<% end %>
		$("#show_questions_link").bind('ajax:success', function(xhr, data, status) {
			$("#show_questions_link").unbind("ajax:success").attr("data-remote", "false").attr("href", "#survey_fromquestion_collapse");
			templateRow = $("#templateQuestionRow");
			addLink = '<%= link_to icon_tag("chevron-left"), add_question_event_path(id: @event.token, question: "__Q__", duration:  quick_start_settings["duration"], format: :js), class: "add_question_link", remote: true, method: :post %>';
			rows = [];
			$.each(data, function(){
				if(this["question_options"]) {
				options = jQuery.map(this["question_options"], function(val, i){
					return "&bull; " + val.name;
				});
				} else {
					options = ["Tag Cloud"];
				}
				current_row = templateRow.clone();
				current_row.attr("data-tags", (this["tags"] || []).join(","));
				current_row.attr("id", "question_row" + this["_id"]);
				current_row.find("td[data-action='add_question']").html(addLink.replace(/__Q__/, this["_id"]["$oid"]));
				current_row.find("td[data-attribute='name']").text(this["name"]).popover({
					title: this["name"],
					content: options.join("<br>"),
					html: true,
					placement: 'top',
					trigger: 'hover'
				});
				current_row.removeClass("hidden");
				rows.push(current_row);
			});
			$("#question-list tbody").append(rows).find("*[data-placement]").popover({html: true, trigger: 'hover'});;
		});
		var reRenderMath = function(){
			if(MathJax !== undefined) {
				MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
			}
		};
		$( document ).on('ajax:success', "a.compare_link", function(xhr, data, status) {
			jQuery("#changed_modal_temp").html(data).modal('show');
			reRenderMath();
		}).on('ajax:error', "a.compare_link", function() {
			alert("Leider fuer diese Umfrage nicht verfuegbar.\nUnfortunately, not available for this survey.");
		});
		$( document ).on('ajax:success', "a.compare_modal_link", function(xhr, data, status) { // inner dropdown
			jQuery("#changed_modal_body").html(data);
			reRenderMath();
		}).on('ajax:error', "a.compare_modal_link", function() {
			alert("Leider fuer diese Umfrage nicht verfuegbar.\nUnfortunately, not available for this survey.");
		});
	$( document ).on('ajax:success', "a.comment_modal_link", function(xhr, data, status) {
		jQuery("#changed_modal_temp").html('<div class="modal-dialog"><div class="modal-content"><div class="modal-body"><a class="close" data-dismiss="modal">&times;</a>' + data + '</div></div></div>').modal('show');
	}).on('ajax:error', "a.comment_modal_link", function() {
		alert("Leider fuer diese Umfrage nicht verfuegbar.\nUnfortunately, not available for this survey.");
	});
	$(document).on('ajax:error', '#new_question_comment', function(xhr, data, status) {
	alert("Leider ist ein Fehler beim Speichern aufgetreten.\nUnfortunately, an error occurred.");
	});
	</script>
	<% if @event.mathjax? %>
	<script type="text/x-mathjax-config">
	MathJax.Hub.Config({
	tex2jax: {
	inlineMath: [ ['$','$'] ],
	processEscapes: true
	}
	});
	</script>
	<%= mathjax_tag %>
	<% end %>
	<script>
	if (window.fullScreenApi.supportsFullScreen) {
		$("#fullscreenLink").bind("click", function(){
			window.fullScreenApi.requestFullScreen($("#fullscreen").get(0));
		}).show();
	}
	</script>
	<% end %>
</div>

<div id="changed_modal_temp" class="modal fade">
	<!-- will be shown for comparison of answering behaviour and comments -->
</div>


<p><%= link_to t("back"), events_path %></p>
<% unless ENV["USE_JUGGERNAUT"] == "false" %>
<% content_for :javascript do %>
<script>
// refresh connected timer every five seconds
window.PINGO.events.vars.startConnectedUsersUpdateInterval = window.PINGO.events.startConnectedUsersUpdate("<%= @event.token %>", "#connected-number", "#connected-container", 5);
</script>
<% end %>
<% end %>
<% if params[:tour] == "true" %>
	<%= render "tours/enable_tour" %>
	<%= render "tours/events/show", surveys_empty: @event.surveys.empty? %>
<% end %>
<!-- QR code for session -->
<%= render "events/qr", event: @event %>