config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  post "find" => "events#find"
  post "vote" => "surveys#vote"
  post "quick_start" => "events#quick_start"

  post "api/get_auth_token" => "api#get_auth_token"
  post "api/check_auth_token" => "api#check_auth_token"
  post "api/save_ppt_settings" => "api#save_ppt_settings"
  post "api/save_question" => "api#save_question"
  get "api/load_ppt_settings" => "api#load_ppt_settings"
  get "api/load_ppt_list" => "api#load_ppt_list"
  post "api/delete_ppt_settings" => "api#delete_ppt_settings"
  get "api/question_types" => "api#question_types"
  get "api/duration_choices" => "api#duration_choices"
  get "api/me" => "api#me"

  get "api/find_user_by_email" => "api#find_user_by_email"
  get "api/me" => "api#me"

  get "stats" => "home#stats", as: :stats
  get "switch_view" => "home#switch_view"

  get "api/:cmd" => "surveys#api"

  post "vote-test" => "surveys#vote_test"

  devise_for :users, :controllers => {:registrations => 'settings'}

  devise_scope :user do
    post "users/reset_api_token" => "settings#reset_auth_token", as: :reset_auth_token
  end

  resources :events do
    member do
      post "quick_start" => "surveys#quick_start"
      post "add_question" => "events#add_question"
      post "exit_question" => "surveys#exit_question"
      get "connected" => "events#connected_users"
      get "export"
      get "latest_survey" => "events#latest_survey"
    end
    resources :surveys do
      member do
        post 'start'
        post 'stop'
        post 'repeat'
        get 'changed'
        get 'changed_aggregated'
        get 'results'
      end
    end
  end

  resources :questions do
    member do
      post 'add_to_own'
    end
    resources :question_comments, only: [:create, :destroy, :index]
    collection do
      post "export"
      get 'import'
      post 'upload'
      post 'share'
    end
  end
  post "questions/:id/transform" => "questions#transform", as: "transform_question"

  get "invitations/new", :as => "invitation"
  post "invitations/deliver", :as => "deliver_invitation"

  get "newsletter_confirm/:token" => "home#newsletter"

  namespace :admin do
    resources :users
    get 'voting_analytics' => 'users#voting_analytics'
  end
  
  get ":id" => "surveys#participate", :constraints => {:id => /[0-9]+/}, :as => :participate

  mount Amnesia::Application.new => "/amnesia" if defined?(Amnesia)

  mount Pingohort::Engine, at: "/pingohort" if defined?(Pingohort)

end

app/models/survey.rb
class Survey
  
  include Mongoid::Document
  include Mongoid::Timestamps
  
  include ActiveModel::ForbiddenAttributesProtection # #rails4

  after_save :delete_cache, :refresh_event_state

  belongs_to :original_survey, class_name: "Survey", inverse_of: :repeated_surveys, optional: true
  has_many :repeated_surveys, class_name: "Survey", inverse_of: :original_survey
  
  embeds_many :options
  accepts_nested_attributes_for :options, :allow_destroy => true
    
  field :name, type: String
  field :description, type: String
  
  field :starts, type: DateTime
  field :ends, type: DateTime
  
  field :voters, type: Array
  field :voters_hash, type: Hash
  field :voters_hash_numbers, type: Array
  field :voters_hash_words, type: Array
  
  field :quick, type: Boolean
  field :multi, type: Boolean
  field :exit_q, type: Boolean, default: false

  field :settings, type: Hash, default: {}
  
  field :type, type: String
  validates :type, inclusion: {in: Question.question_types}

  belongs_to :event, index: true
  
  belongs_to :question, optional: true

  scope :current, ->{ where(:starts.gte => DateTime.now).and(:ends.lt => DateTime.now) }
  scope :display_fields, ->{ only(:description, :ends, :name, :options, :starts, :event_id, :quick, :created_at, :multi, :type, :settings, :voters, :voters_hash, :voters_hash_numbers, :voters_hash_words,:original_survey_id, :exit_q, :question_id) }
  scope :participate_fields, ->{ only(:description, :ends, :name, :options, :starts, :event_id, :quick, :multi, :type, :exit_q, :settings) }
  scope :worker_fields, ->{ only(:voters, :multi, :type, :starts, :ends) }
  
  validates :event, presence: true
  
  # this is where we setup getting the service objects
  def service
    case type 
    when "text"
      TextSurvey.new(self)
    when "single"
      SingleChoiceSurvey.new(self)
    when "multi"
      MultipleChoiceSurvey.new(self)
    when "number"
      NumberSurvey.new(self)
    when "exit_q"
      ExitSurvey.new(self)
    else
      self
    end
  end
  
  def user
    self.event.user
  end
  
  def collaborators
    self.event.collaborators || []
  end
  
  def total_votes
    unless self.voters.nil?
      self.voters.count
    else
      0
    end
  end
  
  def running?(strict = true)
    self.starts && self.starts <= DateTime.now && ((self.ends && self.ends > (DateTime.now - (strict ? 0 : 1.seconds))) || self.ends.nil?)
  end
  
  def start!(duration = 0)
    return false if self.running?(true)
    self.ends = nil
    self.ends = DateTime.now + duration.seconds unless duration == 0
    self.starts = DateTime.now
    self.save!
  end
  
  def stop!(duration = 0)
    return false unless self.running?(true)
    self.ends = DateTime.now + duration.seconds
    self.save!
  end

  
  def time_left(milliseconds = false)
    m = (milliseconds ? 1000 : 1)
    return 0 if !self.running? || !self.ends
    ((self.ends - DateTime.now) * 24 * 60 * 60 * m).to_i
  end

  # :nocov:
  def track_vote(vid)
    if ENV["ANALYTICS"] == "true"
      begin #  we do not want anything from this tracking to produce an error
        a_vote = Vote.new
        a_vote.time_left = self.time_left(true)
        a_vote.session_uri = self.event.token.to_s+"/"+self.id.to_s
        a_vote.duration = ((self.ends - self.starts) * 24 * 60 * 60).to_i if self.ends
        a_vote.voter_id = vid.to_s
        a_vote.save!
      rescue ; end
    end
  end
  # :nocov:
  
  def mathjax?
    self.event.mathjax?
  end
  

  private
  def delete_cache
    puts "Deleting cache..." if Rails.env.development?
    Rails.cache.delete("Surveys/"+self.id.to_s)
    Rails.cache.delete("last_survey/"+self.event.id.to_s)
    self.event.delete_cache
  end
  
  def refresh_event_state
    self.event.refresh_state
  end  
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_filter :authenticate_user!, :except => [:vote, :vote_test, :participate]

  layout :detect_browser #, :only => [:participate, :find]

  # GET /events/:event_id/surveys
  # GET /events/:event_id/surveys.json
  def index
    @event = Event.find_by_id_or_token(params[:event_id])
    render text: t("messages.no_access_to_session"), status: :forbidden and return  if !@event.nil? && !current_user.admin && @event.user != current_user && !@event.collaborators.include?(current_user)
    
    return if performed?
    
    @surveys = @event.surveys.display_fields.desc(:created_at)

    respond_to do |format|
      format.html { render partial: "events/surveys_table", locals: {event: @event} }
      format.json { send_data @surveys.to_json, 
                              :type => 'json; charset=utf-8; header=present', 
                              :filename => 'PINGO_surveys_'+@event.token+'_'+Time.current.to_s.tr(" ", "_")+'.json' 
                  }
    end
  end

  # GET /events/:event_id/surveys/1
  # GET /events/:event_id/surveys/1.json
  def show
    @survey = Survey.display_fields.find(params[:id]).service
    check_access
    return if performed?

    respond_to do |format|
      set_locale_for_event_or_survey
      format.html {
        if params[:remote_view] == "true"
         render "surveys/show_remote", layout: false
        elsif params[:ppt_view] == "true"
          render "surveys/show_ppt", layout: false
        else
          @event = @survey.event
          @surveys = @event.surveys.display_fields.desc(:created_at) #map(:service)
          @load_survey = @survey

          render "events/show"
        end
      }
      format.js
      format.json { render json: @survey }
    end
  end

  # GET /events/:event_id/surveys/new
  # GET /events/:event_id/surveys/new.json
  def new
    @survey = Survey.new
    @survey.options.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /events/:event_id/surveys/1/edit
  def edit
    @survey = Survey.display_fields.find(params[:id]).service
  end

  # POST /events/:event_id/surveys
  # POST /events/:event_id/surveys.json
  def create
    @event = Event.find_by_id_or_token(params[:event_id])
    @survey = Survey.new(survey_params)
    @survey.event = @event

    render :text => t("messages.no_access_to_session"), :status => :forbidden and return  if !@event.nil? && !current_user.admin && @event.user != current_user

    respond_to do |format|
      if @survey.save
        format.html { redirect_to event_survey_path(@survey.event, @survey), notice: t("messages.survey_successfully_created") }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/:event_id/surveys/1
  # PUT /events/:event_id/surveys/1.json
  def update
    @survey = Survey.find(params[:id]).service

    check_access
    return if performed?

    respond_to do |format|
      if @survey.update_attributes(survey_params)
        format.html { redirect_to event_survey_path(@survey.event, @survey), notice: t("messages.survey_successfully_updated") }
        format.json { render :text => "" }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/:event_id/surveys/1
  # DELETE /events/:event_id/surveys/1.json
  def destroy
    @survey = Survey.find(params[:id])

    check_access
    return if performed?

    publish_push_notification("s"+@survey.id.to_s, {:type => "status_change", :payload => "stopped", "timestamp" => Time.new})

    @survey.destroy

    respond_to do |format|
      format.html { redirect_to event_path(@survey.event) }
      format.json { head :ok }
    end
  end


  # GET /:id
  def participate
    @event = Rails.cache.read("Events/"+params[:id])
    unless @event
      begin
        pprint "getting event from DB (no cache)"
        @event = Event.find_by_id_or_token(params[:id])
        Rails.cache.write("Events/"+params[:id], @event, :expires_in => 5.seconds)
      rescue ; end    #rescue errors like BSON::InvalidObjectId (if people enter neither a token nor a proper Mongo ID)
    end

    respond_to do |format|
      format.html { #normal view
        redirect_to root_path, alert: t("messages.survey_not_found") and return if @event.nil?
        @survey = Rails.cache.read("last_survey/"+params[:id])
        unless @survey
          pprint "getting survey from DB (no cache)"
          @survey = @event.latest_survey("participate").try(:service)
          Rails.cache.write("last_survey/"+params[:id], @survey, :expires_in => 1.seconds)
        end
      }
      format.json { render json: @event.state } # state info to update view if neccessary
    end
  end

  # POST /events/:event_id/surveys/1/start
  def start
    @survey = Survey.display_fields.find(params[:id]).service
    @event = @survey.event
    check_access
    return if performed?

    if(is_numeric?(params[:stoptime]))
      @survey.start!(params[:stoptime].to_i)
      if params[:stoptime].to_i > 0
        publish_push_notification("s"+@survey.id.to_s, {:type => "status_change", :payload => "started_with_end", "timestamp" => Time.new})
        start_countdown_worker(@survey.id)
      else
        publish_push_notification("s"+@survey.id.to_s, {:type => "status_change", :payload => "started", "timestamp" => Time.new})
      end
    else
      @survey.start!
      publish_push_notification("s"+@survey.id.to_s, {:type => "status_change", :payload => "started", "timestamp" => Time.new})
    end
    respond_to do |format|
      set_locale_for_event_or_survey
      format.html { redirect_to event_survey_path(@survey.event, @survey), notice: t('messages.survey_started') }
      format.js { render "events/add_question" }
    end
  end

  # POST /events/:event_id/surveys/1/stop
  def stop
    @survey = Survey.display_fields.find(params[:id]).service
    @event = @survey.event
    check_access
    return if performed?

    if(is_numeric?(params[:stoptime]) && params[:stoptime].to_i > 0)
      @survey.stop!(params[:stoptime].to_i)
      publish_push_notification("s"+@survey.id.to_s, {:type => "status_change", :payload => "stop_scheduled", "time" => @survey.time_left(true), "timestamp" => Time.new})
      start_countdown_worker(@survey.id)
      flash_notice = t('messages.survey_stop_scheduled')
    else
      @survey.stop!
      publish_push_notification("s"+@survey.id.to_s, {:type => "status_change", :payload => "stopped", "timestamp" => Time.new})
      flash_notice = t('messages.survey_stopped')
    end
    respond_to do |format|
      set_locale_for_event_or_survey
      format.html { redirect_to event_survey_path(@survey.event, @survey), notice: flash_notice }
      format.js { render "events/add_question" }
    end
  end

  # POST /events/:event_id/surveys/1/repeat
  def repeat
    @event = Event.find_by_id_or_token(params[:event_id])
    original_survey = Survey.find(params[:id])

    render :text => t("messages.no_access_to_session") and return  if !@event.nil? && !current_user.admin && @event.user != current_user

    @survey = Survey.new
    @survey.event = @event
    @survey.name = original_survey.name
    @survey.quick = true
    original_survey.options.map do |option|
      @survey.options.new(name: option.name, correct: option.correct)
    end
    @survey.type = original_survey.type
    @survey.settings = original_survey.settings
    @survey.original_survey = original_survey
    duration = (is_numeric?(params[:duration]) ? params[:duration].to_i : 0)

    respond_to do |format|
      set_locale_for_event_or_survey
      if @survey.save
        @survey.service.start!(duration)
        publish_push_notification("sess"+@survey.event.token.to_s, {:type => "status_change", :payload => "started", "timestamp" => Time.new})
        start_countdown_worker(@survey.id) if duration > 0
        format.html { redirect_to event_path(@survey.event), notice: t("messages.survey_successfully_created") }
        format.js { render "events/add_question" }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /vote
  def vote
    redirect_to root_path, alert: t("messages.misc_error") if params[:id].blank?

    @vid = get_or_create_voter_id
    @survey = Survey.find(params[:id]).service
    @user_just_voted = false
    redirect_to "/"+@survey.event.to_param, alert: t("messages.no_option_error") and return if (params[:option].blank? && !@survey.multi)

    if @survey.vote(@vid, params[:option])
      respond_to do |format|
        format.html {
          if @survey.has_options?
            if @survey.type == "multi"
              unless params[:option].nil?
                voted_for = "<br>"+params[:option].map { |o| ("- "+@survey.options.only(:name).find(o).name)+"<br>"}.join
              else
                voted_for = t("matrix_keys.no_answer")
              end
            else
              voted_for = @survey.options.only(:name).find(params[:option]).name
            end
          else
            if params[:option].respond_to? :each
              voted_for = " " + params[:option].reject {|o| o.blank? }.join(", ")
            else
              voted_for = params[:option]
            end
          end
          @user_just_voted = true
          redirect_to "/"+@survey.event.to_param, notice: (t("messages.voting_ok") + " " + t("messages.voted_for", option: voted_for)).html_safe
        }
        format.json { head :ok }
      end
    else
      respond_to do |format|

app/helpers/surveys_helper.rb
module SurveysHelper
  def word_count_js_array(survey)
    survey.word_counts.map do |word, count|
      {text: word, weight: count}
    end
  end
end

app/views/surveys/_form.html.erb
<%= semantic_form_for @survey.to_model, url: event_survey_path do |form| %>
<%= error_msg_for @survey %>

<%= form.input :name %>
<!-- <%= form.input :description, :input_html => { :class => 'autogrow', :rows => 10, :cols => 20  }%> -->

<% if @survey.has_options? %>
<div id="options">
	<h3><%= t("surveys.edit.options_for_survey") %></h3>
	<%= form.semantic_fields_for :options, :class => "form-inline" do |option| %>
		<%= render "option_fields", :f => option %>
	<% end %>
    <div class="form-group">
        <%= link_to_add_association icon_tag("plus")+t("surveys.edit.add_option"), form, :options %>
    </div>
</div>
<% end %>
<div class="form-group">
   <%= form.submit t("update"), :class => "btn btn-primary" %>
</div>
 <% end %>
<% content_for :javascript do %>
  <script>

    $(document).ready(function() {
      $(document).on("change", ".radio_correct_true", function() {
          $(".radio_correct_true").prop('checked', false);
          $(".radio_correct_false").prop('checked', true);
          $(this).prop('checked',true);
      });
    });
  </script>
<% end %>

app/views/surveys/_show.html.erb
<% # note that this view is rendered via JQuery in the show.js.erb
%>

<script>
	show_view = true;
</script>
	<p class="lead"><% if survey.original_survey %><%= icon_tag("repeat", title:t(".repeated"), data: {toggle: "tooltip", placement: "right"}) %> <% end %>
		<span id="survey_name" data-placement="bottom" data-toggle="tooltip" data-delay="100" title="<%= t "survey" %> <%= t ".from" %> <%= l(survey.created_at) %>"><%= survey.name || t(".survey") %></span>

      <%= link_to icon_tag("comment"), question_question_comments_path(survey.question, survey_id: survey.id), title: t("comment"), remote: true, class: "comment_modal_link", data: {toggle: "tooltip", placement: "bottom"} if survey.question.present? %>
    </p>


	<% unless survey.description.blank? %>
		<p><strong><%= t ".description"%>:</strong> <%= h survey.description %></p>
	<% end %>

	<% if survey.type == "multi" %>
		<p><%= t ".is_multi" %></p>
	<% end %>
	<% if survey.type == "text" %>
		<p><%= t ".is_text" %></p>
	<% end %>

	<!--<% if survey.running?(true) %>
		<p id="running-notice">
		<small><%= t(".running_notice", :url => ENV["URL_PREFIX"]+"/"+survey.event.token.to_s).html_safe %><br/>
			<% if survey.ends %>
				 <%= t ".end" %>: <%= I18n.localize(survey.ends.in_time_zone) %>.
			<% end %>
		</small></p>
		<% if survey.ends %>
			<% if current_user.wants_sound %>
				<audio id="sound" preload="auto" style="display:none">
  					<source src="/bell_sound.mp3" type="audio/mpeg" />
  					<source src="/bell_sound.OGG" type="audio/ogg" />
				</audio>
			<% end %>
		<% end %>
	<% end %> -->
	<%= render partial: "survey_running", locals: {survey: @survey} %>



<!--
<p>
<small><%= link_to t("edit"), edit_event_survey_path(survey.event, survey) %></small>
</p>
//-->
<% if survey.has_options? and survey.options.count > 0 %>
	<section class="option-results">
		<p><strong><%= t ".options" %>:</strong></p>

		<ul id="survey-options-list" class="no-bullets">
			<%= render partial: "option", collection: survey.options %>
		</ul>

		<div class="chart-container hide-button">
			<h4 class="chart-container__heading text-center"><%= t("results") %> (%)</h4>

			<div class="canvas_downloadable clearfix">
				<canvas id="chart" height="300" class="chart-container__chart"></canvas>
				<a href="#chart" class="btn btn-default canvas_download-button" id="save_chart_btn" download="pingo_chart.png"><%= icon_tag("download-alt") %></a>

				<% if survey.options.any?(&:correct) %>
				<a class="btn btn-default pull-right canvas__show-highlight" id="show-highlights" data-toggle="button"><%= t(".mark_correct") %></a>
				<% end %>

    <% if survey.original_survey %>
				<ul class="chart-container__legend legend">
					<li class="legend__item legend__item--first"><%= t("surveys.show.chart_first") %></li>
					<li class="legend__item legend__item--repeated"><%= t("surveys.show.chart_repeated") %></li>
				</ul>
			</div>
		<% end %>
		</div>
	</section>

<% elsif survey.type == "text" %>
 <% if !survey.running? && survey.total_votes > 0 %>
   	<div class="btn-group">
   <button class="btn btn-small dropdown-toggle btn-default" data-toggle="dropdown"><%= t(".switch_view") %> <span class="caret"></span></button>
     <ul class="dropdown-menu close-on-click" role="menu">
       <li><%= link_to t(".tag_cloud"), results_event_survey_path(@survey.event, @survey, view_type: "tag_cloud"), remote: true %></li>
       <li><%= link_to t(".table"), results_event_survey_path(@survey.event, @survey, view_type: "text"), remote: true %></li>
   </ul>
</div>
   <div id="detailed_results">
  <% if survey.total_votes > 6 %>
	<%= render "text_tag_cloud_result", survey: @survey %>
  <% else %>
	<%= render "text_table_results", survey: @survey %>
  <% end %>
    </div>

 <% else %>
	<div style="clear:left;"><%= image_tag "tag_cloud_placeholder.png" %></div>
  <% end %>




<% elsif survey.type == "number" %>
    <% if !survey.running? && survey.total_votes > 0 %>
  		<p><%= t (".avg") %>: <%= badge(number_with_precision survey.voting_avg, precision: 2, strip_insignificant_zeros: true) %> </p>
  		<p> <%= t (".stdev") %>: <%= badge(number_with_precision survey.voting_stdev, precision: 2, strip_insignificant_zeros: true) %> </p>
  		<p> <%= t (".median") %>: <%= badge(number_with_precision survey.voting_median, precision: 2, strip_insignificant_zeros: true) %> </p>

        <div class="btn-group">
          <button class="btn btn-default btn-small dropdown-toggle" data-toggle="dropdown"><%= t(".switch_view") %> <span class="caret"></span></button>
          <ul class="dropdown-menu close-on-click">
            <li><%= link_to t(".chart"), results_event_survey_path(@survey.event, @survey, view_type: "clustered_chart", method_kind: "clustered"), remote: true %></li>
            <li><%= link_to t(".histogram"), results_event_survey_path(@survey.event, @survey, view_type: "clustered_chart", method_kind: "histogram"), remote: true %></li>
            <li><%= link_to t(".table"), results_event_survey_path(@survey.event, @survey, view_type: "text"), remote: true %></li>
          </ul>
        </div>
        <div id="detailed_results">
          <% if survey.total_votes > 6 %>
              <%= render "number_clustered_chart_results", survey: @survey %>
          <% else %>
              <%= render "text_table_results", survey: @survey %>
          <% end %>
        </div>

    <% else %>

    <% end %>


<% end %>

<div id="actions" class="well survey-actions">
	<% if survey.running?(true) %>
		<%= form_tag(stop_event_survey_path(survey.event, survey), remote: true, class: "form-inline survey-actions__form") %>
			 <label for="stoptime"><%= submit_tag t(".stop1"), :disable_with => t("wait"), :class => "btn btn-danger" %></label>
			<%= select_tag "stoptime", options_for_select(duration_choices(true), 1), class: "form-control" %>
		</form>
	<% else %>

		<% if survey.event.latest_survey == survey.to_model %>

		 <%= form_tag(start_event_survey_path(survey.event, survey), remote: true, class: "form-inline survey-actions__form") %>
			<%= submit_tag t(".continue1"), :disable_with => t("wait"), :class => "btn btn-success" %>
			<%= hidden_field_tag "stoptime", "120", :id => "hidden_stoptime" %>
	 	 </form>

		<% end %>

		<%= form_tag(repeat_event_survey_path(survey.event, survey), remote: true, class: "form-inline survey-actions__form") %>
			<%= submit_tag t(".repeat1"), :disable_with => t("wait"), :class => "btn btn-success repeat-survey-button" %>
			<%= select_tag "duration", options_for_select(duration_choices(false), 120), class:"form-control", id: "repeatDuration" %>
		</form>

			<script>
			$(document).ready(function() {
		  		$(document).on("change", "#repeatDuration", function() {
		  			$("#hidden_stoptime").val($('#repeatDuration option:selected').val());
		  		});
		  		$(document).on("click", "#save_chart_btn", function(e) {
		  			if($("#chart").length > 0){
		  				var base_str = $("#chart").get(0).toDataURL();
		  				$(this).attr("href", base_str);
		  				return true;
		  			}
		  		});
				if(window.PINGO.isMSIE()){
			  		$(".canvas_downloadable").removeClass("canvas_downloadable");
			  	}
		  	});
		 	</script>
	<% end %>
</div>

app/views/surveys/changed.html.erb
<% unless params[:no_body] == "true" %>
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <a class="close" data-dismiss="modal">&times;</a>
            <h4 class="modal-title"><%= t ".header" %></h4>
        </div>
        <div id="changed_modal_body" class="modal-body">
<% end %>
            <table class="table table-striped table-hover table-condensed">
                <thead>
                    <th><%= icon_tag("arrow-down") %><em><%= t ".from" %></em> <span style="float:right;"><em><%= t ".to" %></em> <%= icon_tag("arrow-right") %></span></th>
                    <% @cols.each do |col| %>
                    <th><%= col.second %></th>
                    <% end %>
                </thead>
                <tbody>
                    <% @rows.each do |row| %>
                    <tr><th><%= row.second %></th>
                    <% @cols.each do |col| %>
                    <td><%= @matrix[[row.first, col.first]] %></td>
                    <% end %>
                </tr>
                <% end %>
            </tbody>
        </table>
<% unless params[:no_body] == "true" %>
        </div>
        <div class="modal-footer" <%= "style=\"height: 80px;\"".html_safe if @survey.correct_answers %>>
            <% if @survey.correct_answers %>
            <div class="btn-group" style="float:left;">
                <button class="btn btn-small dropdown-toggle" data-toggle="dropdown"><%= t(".switch_view") %> <span class="caret"></span></button>
                <ul class="dropdown-menu">
                    <li><%= link_to t(".normal_changes"), changed_event_survey_path(@survey.event, @survey, no_body: "true"), remote: true, class: "compare_modal_link" %></li>
                    <li><%= link_to t(".aggregated_changes"), changed_aggregated_event_survey_path(@survey.event, @survey, no_body: "true"), remote: true, class: "compare_modal_link" %></li>
                </ul>
            </div>
            <% end %>
            <a class="btn btn-primary" data-dismiss="modal"><%= t("close") %></a>
        </div>
    </div>
</div>
<% end %>

app/views/surveys/show.js.erb
// This view is rendered when a survey is requested via Ajax on an event page.

view_url = "<%= event_survey_path(@survey.event, @survey) %>";
event_page = true;

$('tr.info').removeClass("info");
$('tr#row<%= @survey.id %>').addClass("info");

$('#survey-container').slideDown().html("<%= escape_javascript(render partial: 'show', locals: {:survey => @survey} ) %>");

window.PINGO.Init();

$('#survey_name').on('update', function() {
	$('#name-<%= @survey.id.to_s %>').text($(this).data('editable').value);
});

if(!History){
	var History = window.History;
}
if(History){
	History.pushState(null, "<%= @survey.name||"Umfrage" %> [<%= @survey.event.token %>] - PINGO", "<%= event_survey_path(@survey.event, @survey)%>");

	// Inform Google Analytics of the change
	if(typeof ga !== 'undefined'){
    ga("send", "pageview", "<%= event_survey_path(@survey.event, @survey)%>");
	}
}

setVoterCount(<%= @survey.total_votes %>, "<%= @survey.id.to_s %>");

<% if @survey.running?(true) && @survey.ends %>

	startCountdown(<%= @survey.time_left(true)-1000 %>);

	<%= render partial: "show_push" %>

<% end %>

<% if @survey.starts && @survey.starts <= DateTime.now %>

// Draw Chart
<%= render partial: "chart", locals: {:survey => @survey, :selector => "#chart"} %>

<% # TODO  chart only if choice question
%>

<% end %>

// scroll into view (we scroll to h1 since there's a 60px bootstrap menu bar)

$('#survey-container').imagesLoaded(function() {
	$('.container-centered h1').get(0).scrollIntoView(true);
});

if(MathJax !== undefined) {
	MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
}