config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  post "find" => "events#find"
  post "vote" => "surveys#vote"
  post "quick_start" => "events#quick_start"

  post "api/get_auth_token" => "api#get_auth_token"
  post "api/check_auth_token" => "api#check_auth_token"
  post "api/save_ppt_settings" => "api#save_ppt_settings"
  post "api/save_question" => "api#save_question"
  get "api/load_ppt_settings" => "api#load_ppt_settings"
  get "api/load_ppt_list" => "api#load_ppt_list"
  post "api/delete_ppt_settings" => "api#delete_ppt_settings"
  get "api/question_types" => "api#question_types"
  get "api/duration_choices" => "api#duration_choices"
  get "api/me" => "api#me"

  get "api/find_user_by_email" => "api#find_user_by_email"
  get "api/me" => "api#me"

  get "stats" => "home#stats", as: :stats
  get "switch_view" => "home#switch_view"

  get "api/:cmd" => "surveys#api"

  post "vote-test" => "surveys#vote_test"

  devise_for :users, :controllers => {:registrations => 'settings'}

  devise_scope :user do
    post "users/reset_api_token" => "settings#reset_auth_token", as: :reset_auth_token
  end

  resources :events do
    member do
      post "quick_start" => "surveys#quick_start"
      post "add_question" => "events#add_question"
      post "exit_question" => "surveys#exit_question"
      get "connected" => "events#connected_users"
      get "export"
      get "latest_survey" => "events#latest_survey"
    end
    resources :surveys do
      member do
        post 'start'
        post 'stop'
        post 'repeat'
        get 'changed'
        get 'changed_aggregated'
        get 'results'
      end
    end
  end

  resources :questions do
    member do
      post 'add_to_own'
    end
    resources :question_comments, only: [:create, :destroy, :index]
    collection do
      post "export"
      get 'import'
      post 'upload'
      post 'share'
    end
  end
  post "questions/:id/transform" => "questions#transform", as: "transform_question"

  get "invitations/new", :as => "invitation"
  post "invitations/deliver", :as => "deliver_invitation"

  get "newsletter_confirm/:token" => "home#newsletter"

  namespace :admin do
    resources :users
    get 'voting_analytics' => 'users#voting_analytics'
  end
  
  get ":id" => "surveys#participate", :constraints => {:id => /[0-9]+/}, :as => :participate

  mount Amnesia::Application.new => "/amnesia" if defined?(Amnesia)

  mount Pingohort::Engine, at: "/pingohort" if defined?(Pingohort)

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps::Created # save registration date
  
  # Include default devise modules. Others available are:
  # :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable  

# Vor-, Nachname, Lehrstuhl, Fakultät, Welche Lehrveranstaltungen/user comment(nur bei Registrierung)

  field :first_name, type: String
  field :last_name, type: String
  field :chair, type: String
  field :faculty, type: String
  field :organization, type: String
  field :user_comment, type: String

  field :wants_sound, type: Boolean, default: false
  
  field :allow_external_analytics, type: Boolean, default: true
  
  field :newsletter, type: Boolean, default: false

  field :admin, type: Boolean, default: false
  field :email, type: String
  field :encrypted_password, type: String

  field :reset_password_token, type: String ## Recoverable
  field :reset_password_sent_at, type: Time ## Recoverable
  field :remember_created_at, type: Time ## Rememberable

  ## Trackable
  field :sign_in_count, type: Integer
  field :current_sign_in_at, type: Time
  field :last_sign_in_at, type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip, type: String
  
  ## Token authenticatable
  field :authentication_token, type: String
  
  field :quick_start_settings, type: Hash, default: Hash.new

  field :ppt_settings, type: Hash, default: Hash.new
  
  field :newsletter_optin_token, type: String
  field :newsletter_confirmed_at, type: Time, default: nil
  
  validates :first_name, presence: true
  validates :last_name, presence: true

  validates :organization, presence: true
  validates_uniqueness_of :name, :email, case_sensitive: false
  
  #attr_accessible :first_name, :last_name, :faculty, :chair, :organization, :user_comment, :email, :password, :password_confirmation, :remember_me, :wants_sound, :newsletter, :allow_external_analytics, :ppt_settings
  
  has_many :events, dependent: :destroy
  has_many :questions, dependent: :destroy
  
  has_and_belongs_to_many :shared_events, class_name: "Event", inverse_of: :collaborators
  has_and_belongs_to_many :shared_questions, class_name: "Question", inverse_of: :collaborators
  has_and_belongs_to_many :contacts, class_name: "User", inverse_of: nil
  
  
  # returns latest session from user.
  # creates a new one and returns it if the user has no session
  def latest_event
    latest_event = self.events.desc(:created_at).limit(1)[0]
    if latest_event.nil? #oops, user never had a session before...
      latest_event = self.events.build
    end
    latest_event
  end
  
  def voter_id #used as "voter-string" to ensure that logged in users can only vote once
    "USER_"+self.id.to_s
  end

  def name
    [first_name, last_name].join(" ")
  end
  
  def contact_names_and_ids
    (self.contacts || []).map do |c|
      {
        id: c.id.to_s,
        name: c.name
      }
    end
  end

  def question_tags(type = nil)
    if type
      self.questions.in(type: type).pluck(:tags).flatten.uniq if self.questions
    else
      self.questions.pluck(:tags).flatten.uniq if self.questions
    end
  end
  
  def shared_question_tags(type = nil)
    if type
      self.shared_questions.in(type: type).pluck(:tags).flatten.uniq
    else
      self.shared_questions.pluck(:tags).flatten.uniq
    end
  end
  
  def all_question_tags(type = nil)
    (question_tags(type) + shared_question_tags(type)).uniq
  end
  
  
  # https://gist.github.com/josevalim/fb706b1e933ef01e4fb6
  def ensure_authentication_token!
      if authentication_token.blank?
        self.authentication_token = generate_authentication_token
      end
  end
  
  def generate_newsletter_token
      loop do
        random_token = SecureRandom.urlsafe_base64(nil, false)
        break random_token unless User.where(newsletter_optin_token: random_token).any?
      end
  end

    private
  
  def generate_authentication_token
      loop do
        token = Devise.friendly_token
        break token unless User.where(authentication_token: token).first
      end
  end
  
end

app/controllers/admin/users_controller.rb
# :nocov:
class Admin::UsersController < ApplicationController
  require 'csv'
  
  if defined?(NewRelic)
    newrelic_ignore
  end

  before_action :authenticate_user!
  before_action :require_admin

  # GET /admin/users
  # GET /admin/users.json
  def index
    @users = User.order_by([[:created_at, :desc]])
    if params[:all] != "true"
      @users = @users.limit(100)
    end
    start_date = (Date.today - 1.month)
    
    mr_map = "function() { d = new Date(this.created_at); emit({month: d.getMonth() + 1, day: d.getDate() },  1); }"

    mr_reduce = "function(dateObject, registrations) {
      return Array.sum(registrations);
    }"
    
    registrations_mr = User.where(:created_at.gte => start_date.to_time.utc).map_reduce(mr_map, mr_reduce).out(inline: 1)

    # smthg like: select day(users.created_at) as d, month(users.created_at) as m, sum(*) from users where created_at > :x group by (d, m)

    @registrations = {}

    start_date.upto(Date.today) do |day|
      @registrations["#{day.day}.#{day.month}"] = 0
    end

    registrations_mr.each do |reg|
      @registrations["#{reg["_id"]["day"].to_i}.#{reg["_id"]["month"].to_i}"] = reg["value"].to_i
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {users: @users, registrations: @registrations } }
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/1/edit
  def edit
    @user = User.find(params[:id])
    puts @user.inspect
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.json
  def update
    @user = User.find(params[:id])

    # https://github.com/plataformatec/devise/wiki/How-To:-Manage-users-through-a-CRUD-interface
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    @user.admin = (params[:user][:admin] == "1")

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_path }
      format.json { head :ok }
    end
  end

  def voting_analytics
    respond_to do |format|
      format.csv do
        csv_string = CSV.generate do |csv|
          Vote.all.each do |v|
            csv << [v.time_left, v.duration, v.session_uri, v.voter_id]
          end
        end
        render plain: csv_string.to_s
      end
    end
  end

end
# :nocov:

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user_from_token!
 before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>Unfortunately, <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved properly:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <ol><label for="user_first_name">User first name:</label> <br/> <%= f.text_field :first_name %></ol>
 <ol><label for="user_last_name">User last name:</label> <br/> <%= f.text_field :last_name %></ol>
 <ol><label for="user_organization">User organization:</label> <br/> <%= f.text_field :organization %></ol>
 <ol><label for="user_faculty">User faculty:</label> <br/> <%= f.text_field :faculty %></ol>
 <ol><label for="user_chair">User chair:</label> <br/> <%= f.text_field :chair %></ol>
 <ol><label for="user_password">Password:</label> <br/> <%= f.password_field :password %> 
<% unless @user.new_record? %> <small>(only when changing passwords) </small><% end %>
 </ol>
 <ol><label for="user_password_confirmation">...confirm:</label> <br/> <%= f.password_field :password_confirmation %> 
<% unless @user.new_record? %> <small>(only when changing passwords) </small><% end %>
 </ol>
 <ol><label for="user_email">E-Mail:</label> <br/> <%= f.email_field :email %></ol>
 <ol><label for="user_admin">Admin privileges:</label> <br/> <%= f.check_box :admin %></ol>
 <ol> <%= f.submit "Save" %> </ol>
<% end %>

app/views/admin/users/edit.html.erb
<div data-role="header">
<h1>Editing user <em><%= @user.name %></em></h1>
</div>
<%= render 'form' %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<% title("Admin") %>
<div data-role="header">
<p><%= link_to "» Session-Spion", events_path(all: true), class: "btn btn-success" %> <%= link_to "» Fragen-Spion", questions_path(all: true), class: "btn btn-warning" %>  <%= link_to "» Stats", stats_path, class: "btn btn-default" %></p>
<h1>Listing users</h1>
</div>
<table class="table table-bordered table-hover table-condensed">
<theader>
  <tr>
	<th>User name</th>
	<th>Organization</th>
    <th>Created at</th>
    <th>Sessions</th>
    <th></th>
    <th></th>
	<th></th>
  </tr>
</theader>
<tbody>
<% @users.each do |user| %>
  <tr>
	<td><%= h user.name %>
    <td><%= user.organization %> <%= user.faculty %> <%= user.chair %></td>
	<td><%= l(user.created_at, :format => :long) if user.created_at %></td>
	<td><%= user.events.count if user.events %></td>
    <td><%= link_to 'Show', admin_user_path(user) %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
	<td>
<% unless user == current_user %>
	<%= link_to 'Delete', admin_user_path(user), "data-confirm" => 'Do you really want to delete the user ' + user.name + '?', method: :delete %>
<% end %>
&nbsp;</td>
  </tr>
<% end %>
</tbody>
</table>
<p>
<%= link_to "show all users (currently showing last 100)", admin_users_path(all: 'true'), class: "btn btn-small", data: { disable_with: "Loading (may take several seconds)" } unless params[:all] == 'true' %><br>
<%= link_to 'New User', new_admin_user_path, :class => "btn" %><br><br>

<h5>Chart: User registrations per day</h5>
<p>
<%= 	Gchart.line(:size => "800x200",
					:data => @registrations.values, :encoding => 'text',
					:max_value =>  @registrations.values.max + 1,
					:axis_with_labels => 'x,y',
	            	:axis_labels => [@registrations.keys, [@registrations.values.min, (@registrations.values.min + @registrations.values.max + 1) / 2, @registrations.values.max + 1]],
					:format => 'image_tag',
					:custom => 'chxs=0,383838,9,-1,t,383838' # smaller x-axis labels
					).html_safe
%>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<div data-role="header">
<h1>Show user details</h1>
</div>
<div id="basic">
	<p><strong>Name:</strong> <%= h @user.name %> </p>
	<p><%= @user.organization %> <%= @user.faculty %> <%= @user.chair %></p>
	<p><strong>Planned use: </strong><%= (@user.user_comment.blank? ? icon_tag("ban-circle") : @user.user_comment) %> </p>
	<p><strong>E-Mail:</strong> <%= mail_to @user.email %>
	<% unless @user.events.blank? %>
		<p><strong>sessions created:</strong> <%= h @user.events.count %></p>
	<% end %>
	<% unless @user.questions.blank? %>
		<p><strong>questions created:</strong> <%= h @user.questions.count %></p>
	<% end %>
</div>
<p>
<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>
</p>